export interface DwCaja {
    id: number;
    sisOrigen: string;
    idGecos?: number | null;
    idInnova?: number | null;
    numberInnova?: string | null;
    extNumInnova?: string | null;
    fixCodeInnova?: string | null;
    extCodeInnova?: string | null;
    cl?: number | null;
    idUniProceso?: number | null;
    uniProceso?: string | null;
    codProducto?: string | null;
    nomProducto?: string | null;
    nomCortoProducto?: string | null;
    idTipoProducto?: number | null;
    nomTipoProducto?: string | null;
    pesoNeto?: number | null;
    pesoBruto?: number | null;
    tara?: number | null;
    unidades?: number | null;
    turno?: number | null;
    destino?: string | null;
    idDesvio?: number | null;
    nomDesvio?: string | null;
    fechaProducido?: Date | null;
    fechaCorrida?: Date | null;
    fechaFaena?: Date | null;
    fechaRegistro: Date;
    fechaCerrado?: Date | null;
    fechaModificacion?: Date | null;
    fechaCongelado?: Date | null;
    fechaVencimiento1?: Date | null;
    fechaVencimiento2?: Date | null;
    idPallet?: number | null;
    idContenedor?: string | null;
    codCliente?: string | null;
    nomCliente?: string | null;
    codBarras?: string | null;
    especie?: string | null;
    estado?: string | null;
    tipo?: number | null;
}
